from enum import Enum


class ValidationScope(Enum):
    """Validation scope categories."""
    CONNECTIVITY = 'CONNECTIVITY'
    UTILITY = 'UTILITY'
    FLOW = 'FLOW'
    MATERIAL = 'MATERIAL'
    QA = 'QA'
    SCENARIO = 'SCENARIO'


class Severity(Enum):
    """Validation error severity levels."""
    INFO = 'INFO'
    WARNING = 'WARNING'
    ERROR = 'ERROR'
    CRITICAL = 'CRITICAL'


class ValidationType(Enum):
    """Types of validation tests."""
    STRUCTURAL = 'STRUCTURAL'
    LOGICAL = 'LOGICAL'
    PERFORMANCE = 'PERFORMANCE'
    COMPLIANCE = 'COMPLIANCE'


class ObjectType(Enum):
    """Test Object Type"""
    NODE = 'NODE'
    LINK = 'LINK'
    POC = 'POC'
    SEGMENT = 'SEGMENT'
    PATH = 'PATH'


class ErrorType(Enum):
    """Validation error types."""
    NOT_FOUND = 'NOT_FOUND'
    NOT_FOUND_NODE = 'NOT_FOUND_NODE'
    NOT_FOUND_LINK = 'NOT_FOUND_LINK'
    NOT_FOUND_NODES = 'NOT_FOUND_NODES'
    NOT_FOUND_LINKS = 'NOT_FOUND_LINKS'
    NOT_USED = 'NOT_USED'
    NOT_USED_POC = 'NOT_USED_POC'
    MISSING = 'MISSING'
    MISSING_GUID = 'MISSING_GUID'
    MISSING_NWO_TYPE = 'MISSING_NWO_TYPE'
    MISSING_START_NODE = 'MISSING_START_NODE'
    MISSING_END_NODE = 'MISSING_END_NODE'
    MISSING_COST = 'MISSING_COST'
    MISSING_DATA_CODE = 'MISSING_DATA_CODE'
    MISSING_UTILITY = 'MISSING_UTILITY'
    MISSING_MATERIAL = 'MISSING_MATERIAL'
    MISSING_FLOW = 'MISSING_FLOW'
    MISSING_POC = 'MISSING_POC'
    MISSING_MARKERS = 'MISSING_MARKERS'
    MISSING_REFERENCE = 'MISSING_REFERENCE'
    USAGE_STATUS = 'USAGE_STATUS'
    BROKEN_CONTINUITY = 'BROKEN_CONTINUITY'
    DISCONNECTED = 'DISCONNECTED' 
    DISCONNECTED_LINK = 'DISCONNECTED_LINK'
    BIDIRECTIONAL_ISSUE = 'BIDIRECTIONAL_ISSUE'
    CONNECTING_GAP = 'CONNECTING_GAP'
    CONTINUITY = 'CONTINUITY'
    CROSS_CONTAMINATION = 'CROSS_CONTAMINATION'
    UNUSUAL = 'UNUSUAL'
    UNUSUAL_LENGTH = 'UNUSUAL_LENGTH'
    UNUSUAL_TOPOLOGY = 'UNUSUAL_TOPOLOGY'
    NEGATIVE_COST = 'NEGATIVE_COST'
    HIGH_COMPLEXITY = 'HIGH_COMPLEXITY'
    REDUNDANT_NODES = 'REDUNDANT_NODES'
    CIRCULAR_LOOP_DETECTED = 'CIRCULAR_LOOP_DETECTED'
    INCOMPATIBILITY = 'INCOMPATIBILITY'
    FLOW_DIRECTION_ISSUE = 'FLOW_DIRECTION_ISSUE'
    MISMATCH = 'MISMATCH'
    UTILITY_MISMATCH = 'UTILITY_MISMATCH'
    MATERIAL_MISMATCH = 'MATERIAL_MISMATCH'
    FLOW_MISMATCH = 'FLOW_MISMATCH'
    INVALID = 'INVALID'
    INVALID_NODE = 'INVALID_NODE'
    INVALID_LINK = 'INVALID_LINK'
    INVALID_START_NODE = 'INVALID_START_NODE'
    INVALID_END_NODE = 'INVALID_END_NODE'
    INVALID_TRANSITION = 'INVALID_TRANSITION'
    INVALID_CHANGE = 'INVALID_CHANGE'
    INVALID_LENGTH = 'INVALID_LENGTH'
    INVALID_UTILITY = 'INVALID_UTILITY'
    INVALID_MATERIAL = 'INVALID_MATERIAL'
    INVALID_FLOW = 'INVALID_FLOW'
    WRONG = 'WRONG'
    WRONG_UTILITY = 'WRONG_UTILITY'
    WRONG_MATERIAL = 'WRONG_MATERIAL'
    WRONG_FLOW = 'WRONG_FLOW'


class TagType(Enum):
    """Tag type categories for AI training."""
    QA = 'QA'           # Quality assurance tags
    RISK = 'RISK'       # Risk assessment tags
    INS = 'INS'         # Inspection tags
    CRIT = 'CRIT'       # Critical issue tags
    UTY = 'UTY'         # Utility-related tags
    CAT = 'CAT'         # Categorization tags
    DAT = 'DAT'         # Data quality tags
    FAB = 'FAB'         # Fabrication-specific tags
    SCENARIO = 'SCENARIO'  # Scenario-specific tags


class TagCode(Enum):
    """Specific tag codes for AI training."""
    # Connectivity tags
    CONN_VALID = 'CONN_VALID'
    CONN_BROKEN = 'CONN_BROKEN'
    CONN_PARTIAL = 'CONN_PARTIAL'
    CONN_COMPLEX = 'CONN_COMPLEX'
    
    # Utility tags
    UTY_CONSISTENT = 'UTY_CONSISTENT'
    UTY_MIXED = 'UTY_MIXED'
    UTY_TRANSITION = 'UTY_TRANSITION'
    UTY_MISSING = 'UTY_MISSING'
    
    # Quality tags
    QA_PASSED = 'QA_PASSED'
    QA_FAILED = 'QA_FAILED'
    QA_REVIEW = 'QA_REVIEW'
    QA_ANOMALY = 'QA_ANOMALY'
    
    # Risk tags
    RISK_HIGH = 'RISK_HIGH'
    RISK_MEDIUM = 'RISK_MEDIUM'
    RISK_LOW = 'RISK_LOW'
    RISK_CONTAMINATION = 'RISK_CONTAMINATION'
    
    # Performance tags
    PERF_OPTIMAL = 'PERF_OPTIMAL'
    PERF_SUBOPTIMAL = 'PERF_SUBOPTIMAL'
    PERF_SLOW = 'PERF_SLOW'
    PERF_EXPENSIVE = 'PERF_EXPENSIVE'
    
    # Structural tags
    STRUCT_SIMPLE = 'STRUCT_SIMPLE'
    STRUCT_COMPLEX = 'STRUCT_COMPLEX'
    STRUCT_REDUNDANT = 'STRUCT_REDUNDANT'
    STRUCT_VIRTUAL = 'STRUCT_VIRTUAL'
    
    # Scenario tags
    SCENARIO_COMPATIBLE = 'SCENARIO_COMPATIBLE'
    SCENARIO_INCOMPATIBLE = 'SCENARIO_INCOMPATIBLE'
    SCENARIO_SPECIFIC = 'SCENARIO_SPECIFIC'


# ErrorScope uses ValidationScope - no separate enum needed
ErrorScope = ValidationScope