from enum import Enum


class ValidationScope(Enum):
    """Validation scope categories."""
    CONNECTIVITY = 'CONNECTIVITY'
    FLOW = 'FLOW'
    MATERIAL = 'MATERIAL'
    FLOW = 'FLOW'
    QA = 'QA'
    SCENARIO = 'SCENARIO'


class Severity(Enum):
    """Validation error severity levels."""
    INFO = 'INFO'
    WARNING = 'WARNING'
    ERROR = 'ERROR'
    CRITICAL = 'CRITICAL'


class ValidationType(Enum):
    """Types of validation tests."""
    STRUCTURAL = 'STRUCTURAL'
    LOGICAL = 'LOGICAL'
    PERFORMANCE = 'PERFORMANCE'
    COMPLIANCE = 'COMPLIANCE'

class ObjectType(Enum):
    """Test Object Type"""
    NODE = 'NODE'
    LINK = 'LINK'
    POC = 'POC'
    SEGMENT= 'SEGMENT'
    PATH = 'PATH'


class TagType:
    """Tag type enum."""
    UTILITY = 'UTY'
    INSPECTION = 'INS'
    CRITICALITY= 'CRIT'
    RISK= 'RISK'
    QA= 'QA'


class TagCode(Enum):
    """Tag code enum."""
    NOT_FOUND = 'NOT_FOUND'
    NOT_FOUND_NODE = 'NOT_FOUND_NODE'
    NOT_FOUND_LINK = 'NOT_FOUND_LINK'
    NOT_FOUND_NODES = 'NOT_FOUND_NODES'
    NOT_FOUND_LINKS = 'NOT_FOUND_LINKS'
    NOT_USED = 'NOT_USED'
    NOT_USED_POC = 'NOT_USED_POC'
    MISSING = 'MISSING'
    MISSING_GUID = 'MISSING_GUID'
    MISSING_NWO_TYPE = 'MISSING_NWO_TYPE'
    MISSING_START_NODE = 'MISSING_END_NODE'
    MISSING_END_NODE = 'MISSING_END_NODE'
    MISSING_COST = 'MISSING_COST'
    MISSING_DATA_CODE = 'MISSING_DATA_CODE'
    MISSING_UTILITY = 'MISSING_UTILITY'
    MISSING_MATERIAL = 'MISSING_MATERIAL'
    MISSING_FLOW = 'MISSING_FLOW'
    MISSING_POC = 'MISSING_POC'
    MISSING_MARKERS = 'MISSING_MARKERS'
    MISSING_REFERENCE = 'MISSING_REFERENCE'
    USAGE_STATUS = 'USAGE_STATUS'
    BROKEN_CONTINUITY = 'BROKEN_CONTINUITY'
    DISCONNECTED = 'DISCONNECTED' 
    DISCONNECTED_LINK = 'DISCONNECTED_LINK'
    BIDIRECTIONAL_ISSUE = 'BIDIRECTIONAL_ISSUE'
    CONNECTING_GAP = 'CONNECTING_GAP'
    CONTINUITY = 'CONTINUITY'
    CROSS_CONTAMINATION = 'CROSS_CONTAMINATION'
    UNUSUAL = 'UNUSUAL'
    UNUSUAL_LENGTH = 'UNUSUAL_LENGTH'
    UNUSUAL_TOPOLOGY = 'UNUSUAL_TOPOLOGY'
    NEGATIVE_COST ='NEGATIVE_COST'
    HIGH_COMPLEXITY = 'HIGH_COMPLEXITY'
    REDUNDANT_NODES = 'REDUNDANT_NODES'
    CIRCULAR_LOOP_DETECTED = 'CIRCULAR_LOOP_DETECTED'
    INCOMPATIBILITY = 'INCOMPATIBILITY'
    FLOW_DIRECTION_ISSUE = 'FLOW_DIRECTION_ISSUE'
    MISMATCH = 'MISMATCH'
    UTILITY_MISMATCH = 'UTILITY_MISMATCH'
    MATERIAL_MISMATCH = 'MATERIAL_MISMATCH'
    FLOW_MISMATCH = 'FLOW_MISMATCH'
    INVALID = 'INVALID'
    INVALID_NODE = 'INVALID_NODE'
    INVALID_LINK = 'INVALID_LINK'
    INVALID_S_NODE = 'INVALID_START_NODE'
    INVALID_E_NODE = 'INVALID_END_NODE'
    INVALID_TRANSITION = 'INVALID_TRANSITION'
    INVALID_CHANGE = 'INVALID_CHANGE'
    INVALID_LENGTH = 'INVALID_LENGTH'
    INVALID_UTILITY = 'INVALID_UTILITY'
    INVALID_MATERIAL = 'INVALID_MATERIAL'
    INVALID_FLOW = 'INVALID_FLOW'
    WRONG = 'WRONG'
    WRONG_UTILITY = 'WRONG_UTILITY'
    WRONG_MATERIAL = 'WRONG_MATERIAL'
    WRONG_FLOW = 'WRONG_FLOW'

    
    
    
    
    
